services:
  frontend:
    image: ghcr.io/imsilvz/melpominee-frontend:master
    ports:
      - target: 8011
        published: 8011
        protocol: tcp
        mode: host
    networks:
      - frontend-network
    restart: always

  backend:
    image: ghcr.io/imsilvz/melpominee-backend:master
    ports:
      - target: 80
        published: 8012
        protocol: tcp
        mode: host
    secrets:
      - mail-secrets
    networks:
      - backend-network
    volumes:
      - /srv/melpominee.app/data:/app/data:rw
    restart: always

  database:
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg-password
    secrets:
      - pg-password
    networks:
      - backend-network
    volumes:
      - /srv/melpominee.app/postgresql:/var/lib/postgresql/data:rw
    image: postgres

secrets:
  mail-secrets:
    file: /secrets/mail-secrets.json
  pg-password:
    file: /secrets/pg-password.txt

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge