services:
  frontend:
    image: ghcr.io/imsilvz/melpominee-frontend:master
    ports:
      - target: 8011
        published: 8011
        protocol: tcp
        mode: host
    networks:
      - frontend-network
    restart: always

  backend:
    image: ghcr.io/imsilvz/melpominee-backend:master
    ports:
      - target: 80
        published: 8012
        protocol: tcp
        mode: host
    secrets:
      - mail-secrets
    networks:
      - backend-network
    volumes:
      - /srv/melpominee.app:/app/data:rw
    restart: always

secrets:
  mail-secrets:
    file: /secrets/mail-secrets.json

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge