services:
  frontend:
    image: ghcr.io/imsilvz/melpominee-frontend:latest
    ports:
      - target: 8011
        published: 8011
        protocol: tcp
        mode: host
    networks:
      - frontend-network

  backend:
    image: ghcr.io/imsilvz/melpominee-backend:latest
    ports:
      - target: 80
        published: 8012
        protocol: tcp
        mode: host
    networks:
      - backend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge