services:
  frontend:
    image: ghcr.io/imsilvz/melpominee-frontend:master
    ports:
      - 8004:80
    networks:
      - frontend-network

  backend:
    image: ghcr.io/imsilvz/melpominee-backend:master
    ports:
      - 8005:5000
    networks:
      - backend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge