apiVersion: v1
kind: Service
metadata:
  name: melpominee-frontend
  namespace: melpominee
spec:
  selector:
    app: melpominee-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
