apiVersion: v1
kind: Service
metadata:
  name: melpominee-backend
  namespace: melpominee
spec:
  selector:
    app: melpominee-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
