apiVersion: v1
kind: ServiceAccount
metadata:
  name: melpominee
  namespace: melpominee
  annotations:
    azure.workload.identity/client-id: "703ef771-2404-4cb2-ad06-a1dc2d383cff"
  labels:
    azure.workload.identity/use: "true"
